/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectaco;

import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author 178630
 */
public class Menu_admin extends javax.swing.JFrame {
    FondoPanel fondo=new FondoPanel();
    private final ClaseMaestra admin;
    private static Connection con;

    /**
     * Creates new form Menu_admin
     */
    public Menu_admin(Connection con) {
        this.con = con;
       this.setResizable(false);
          this.setSize(800, 600);
          initComponents();
          this.setLocationRelativeTo(null);
        admin = new ClaseMaestra(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        ofertas = new javax.swing.JButton();
        cuenta = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cliente = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        almace = new javax.swing.JButton();
        almace1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Que desea hacer?");

        ofertas.setBackground(new java.awt.Color(65, 112, 89));
        ofertas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        ofertas.setForeground(new java.awt.Color(255, 255, 255));
        ofertas.setText("Ofertas");
        ofertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertasActionPerformed(evt);
            }
        });

        cuenta.setBackground(new java.awt.Color(65, 112, 89));
        cuenta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        cuenta.setForeground(new java.awt.Color(255, 255, 255));
        cuenta.setText("Eliminar cuenta de cliente");
        cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaActionPerformed(evt);
            }
        });

        inventario.setBackground(new java.awt.Color(65, 112, 85));
        inventario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setText("Consulta de inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(65, 112, 85));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reporte de ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cliente.setBackground(new java.awt.Color(65, 112, 85));
        cliente.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        cliente.setForeground(new java.awt.Color(255, 255, 255));
        cliente.setText("Consulta por cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        almace.setBackground(new java.awt.Color(65, 112, 85));
        almace.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        almace.setForeground(new java.awt.Color(255, 255, 255));
        almace.setText("Agregar producto a almacen");
        almace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almaceActionPerformed(evt);
            }
        });

        almace1.setBackground(new java.awt.Color(65, 112, 85));
        almace1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        almace1.setForeground(new java.awt.Color(255, 255, 255));
        almace1.setText("Consultar pedidos");
        almace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almace1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ofertas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almace1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(almace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ofertas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(almace, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(almace1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ofertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertasActionPerformed
        int opc=0;
        String[] options = new String[] {"Crear Oferta", "Modificar Oferta", "\"Consultar Ofertas"};
        int response = JOptionPane.showOptionDialog(null, "Message", "Title",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
     //   int j=0;
         if(response == 0){
             try{
            float ans;
            ans= Float.parseFloat( JOptionPane.showInputDialog("Ingresse el descuento: "));
      //  j=ans;
             admin.crearOfertas(9, ans);
             
             }catch(HeadlessException | NumberFormatException e){
                             JOptionPane.showMessageDialog(null, "ERROR", "ERROR"+e, JOptionPane.INFORMATION_MESSAGE);

             }
        } 
         if(response == 1){
             
             String[] p = new String[] {"Eliminar oferta", "Modificar Oferta"};
        int r = JOptionPane.showOptionDialog(null, "Message", "Title",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, p, p[0]);
             if(r==0){//eliminar oferta
                 
                  opc= JOptionPane.showInternalConfirmDialog(null, "Esta seguro de eliminar esta oferta?", "Alerta",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
         //   System.out.println(opc);
           if(opc==1){//NO
               JOptionPane.showInternalMessageDialog(null, "Operacion cancelada",
             "Informacion", JOptionPane.INFORMATION_MESSAGE);
               new Menu_admin(con).setVisible(true);
           }if(opc==0){//SI
                JOptionPane.showInternalMessageDialog(null, "Oferta eliminada exitosamente!",
             "Informacion", JOptionPane.INFORMATION_MESSAGE);
              admin.modificarOfertas(1, 9);
                 new Menu_admin(con).setVisible(true);
           }
             
             }if(r==1){//modificar oferta
                  admin.modificarOfertas(2, 9);
             }
         }
         if(response == 2){
             new Ofertas(con).setVisible(true);
         }
    }//GEN-LAST:event_ofertasActionPerformed

    private void cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaActionPerformed
        // TODO add your handling code here:
        String n;
        Atrapalas_aTodas no=new Atrapalas_aTodas();
        if(evt.getSource()==cuenta){
            new Eliminacuenta(con).setVisible(true);
        }
    }//GEN-LAST:event_cuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       admin.reporteVentas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        if(atras==evt.getSource()){
         //  new CreaUs(con).setVisible(true);  
         //Como llamar al main(??
        }
    }//GEN-LAST:event_atrasActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
                new Almacen1(con).setVisible(true);
                admin.consultaAlmacen();
           
        
    }//GEN-LAST:event_inventarioActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        if(cliente == evt.getSource()){
           new Clientes(con).setVisible(true);
        }
    }//GEN-LAST:event_clienteActionPerformed

    private void almaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almaceActionPerformed
             new Ingresar_producto(con).setVisible(true);
//  admin.ingresarProducto();
    }//GEN-LAST:event_almaceActionPerformed

    private void almace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almace1ActionPerformed
       // admin.mostrarPedidos();
       new Pedidos(con, 0, 1).setVisible(true);
    }//GEN-LAST:event_almace1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin(con).setVisible(true);
            }
        });
    
    }
    class FondoPanel extends JPanel{
    private Image imagen;

    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/madere.jpg")).getImage();
        g.drawImage(imagen, 0, 0,getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almace;
    private javax.swing.JButton almace1;
    private javax.swing.JButton atras;
    private javax.swing.JButton cliente;
    private javax.swing.JButton cuenta;
    private javax.swing.JButton inventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ofertas;
    // End of variables declaration//GEN-END:variables
}
